Mangix.Mvc/Mangix.Admin/Areas/Admin/Controllers/SystemManageController.cs
using Mangix.Admin.Framework.Controllers;
using Mangix.Admin.Framework.Controllers.Admin;
using Mangix.Admin.Framework.Menu;
using Mangix.Core.Extensions;
using Mangix.Mapping.SysDomain;
using Mangix.Mapping.SysStore;
using Mangix.Services.Setting;
using Mangix.Services.SysDomain;
using Mangix.Services.SysStore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mangix.Admin.Area.Admin.Controllers
{
    [RoutePrefix("system")]
    [Descriper("系统管理", true, "menu-icon fa fa-desktop")]
    public class SystemManageController : BaseAdminController
    {
        // GET: SystemManager
        // GET: SystemManage
        private ISysStoreService _sysStoreService;
        private ISysDomainService _sysDomainService;
        private ISettingService _settingService;

        public SystemManageController(ISysStoreService sysStoreService,
            ISysDomainService sysDomainService,
            ISettingService settingService)
        {
            this._sysStoreService = sysStoreService;
            this._sysDomainService = sysDomainService;
            this._settingService = settingService;
        }


        /// <summary>
        /// 系统设置
        /// </summary>
        /// <returns></returns>
        [Route("", Name = "systemIndex")]
        [Descriper("系统设置", true, "menu-icon fa fa-caret-right", FatherResource = "Mangix.Admin.Area.Admin.Controllers.SystemManageController")]
        public ActionResult SystemIndex()
        {
            var model = _sysStoreService.getStore();
            return View(model);
        }

        /// <summary>
        /// 系统基础数据设置
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [Route("editStore", Name = "editStore")]
        [Descriper("编辑系统基础设置", false, FatherResource = "Mangix.Admin.Controllers.Area.Admin.SystemManageController.SystemIndex")]
        public JsonResult EditStore(SysStoreMapping model)
        {
            if(!ModelState.IsValid)
            {
                AjaxData.Message = "数据验证未通过";
                return Json(AjaxData, JsonRequestBehavior.DenyGet);
            }
            model.Creator = WorkContext.CurrentUser.Id;
            model.Modifier = WorkContext.CurrentUser.Id;
            _sysStoreService.saveStore(model);
            AjaxData.Status = true;
            AjaxData.Message = "管理系统设置成功";
            return Json(AjaxData, JsonRequestBehavior.DenyGet);
        }

        /// <summary>
        /// 域名设置
        /// </summary>
        /// <returns></returns>
        [ChildActionOnly]
        public PartialViewResult SysDomain()
        {
            var model = _sysDomainService.getAllCache();
            return PartialView(model);
        }

        /// <summary>
        /// 设置站点域名
        /// </summary>
        /// <param name="domainType"></param>
        /// <param name="domain"></param>
        /// <returns></returns>
        [Route("editDomain", Name = "editDomain")]
        [Descriper("编辑域名设置", false, FatherResource = "Baobei.Admin.Areas.Admin.Controllers.SystemManageController.SystemIndex")]
        [HttpPost]
        public JsonResult EditDomain(string wapDomain, string appDomain)
        {
            if (String.IsNullOrEmpty(wapDomain) && String.IsNullOrEmpty(appDomain))
            {
                AjaxData.Message = "请填写域名";
                return Json(AjaxData, JsonRequestBehavior.DenyGet);
            }
            if (!String.IsNullOrEmpty(wapDomain))
            {
                var model = new SysDomainMapping()
                {
                    DomainType = (int)EnumDomainType.移动端,
                    CreationTime = DateTime.Now,
                    Domain = wapDomain.trimSpace().ToLower()
                };
                _sysDomainService.insertDomain(model);
            }
            if (!String.IsNullOrEmpty(appDomain))
            {
                var model = new SysDomainMapping()
                {
                    DomainType = (int)EnumDomainType.APP接口,
                    CreationTime = DateTime.Now,
                    Domain = appDomain.trimSpace().ToLower()
                };
                _sysDomainService.insertDomain(model);
            }
            AjaxData.Status = true;
            AjaxData.Message = "保存完成";
            return Json(AjaxData, JsonRequestBehavior.DenyGet);
        }










    }
}

Mangix.Mvc/Mangix.Admin/Areas/Admin/Views/SystemManage/SysDomain.cshtml
@using Mangix.Mapping.SysDomain
@model IEnumerable<SysDomainMapping>

@using (Html.BeginRouteForm("editDomain", FormMethod.Post, new { @class = "form-horizontal", id = "formDomain", onsubmit = "return false;" }))
{
    @Html.AntiForgeryToken()
    SysDomainMapping wap = null,app =null;
    if (Model != null && Model.Any())
    {
        wap = Model.FirstOrDefault(o => o.DomainType == (int)EnumDomainType.移动端);
        app = Model.FirstOrDefault(o => o.DomainType == (int)EnumDomainType.APP接口);
    }

    <div class="form-group">
        <label class="col-sm-2 control-label no-padding-right" for="form-field-username">Wap域名</label>
        <div class="col-sm-3"> 
            <input type="text" name="wapDomain" class="form-control" value="@(wap?.Domain)" />
            @Html.ValidationMessage("wapDomain")
        </div>
    </div>
    <div class="space-4"></div>
        <div class="form-group">
            <label class="col-sm-2 control-label no-padding-right" for="form-field-username">APP接口</label>
            <div class="col-sm-3"> 
                <input type="text" name="appDomain" class="form-control" value="@(app?.Domain)" />
                @Html.ValidationMessage("appDomain")
            </div>
        </div>
        <div class="clearfix form-actions">
            <div class="col-md-offset-2 col-md-9">
                <button class="btn btn-info" type="submit">
                    <i class="ace-icon fa fa-check bigger-110"></i>
                    保存
                </button>
            </div>
        </div>
}
<script>
    $(function () {
        $('#formDomain').submit(function () {
            if ($(this).valid()) { 
                $(this).ajaxSubmit(function (data) {
                    $.modal.gritter(data);
                });
            }
        });
    });
</script>

Mangix.Mvc/Mangix.Admin/Areas/Admin/Views/SystemManage/SystemIndex.cshtml
@using Mangix.Mapping.SysStore
@model SysStoreMapping

@{
    ViewBag.Title = "系统设置";
} 
    <h1>@ViewBag.Title</h1>
    <hr />

    <div class="row">
        <div class="col-sm-12">
            <div class="tabbable">
                <ul class="nav nav-tabs padding-16">
                    <li class="active">
                        <a data-toggle="tab" href="#edit-settings">
                            <i class="purple ace-icon fa fa-cog bigger-125"></i>
                            系统设置
                        </a>
                    </li>
                    <li>
                        <a data-toggle="tab" href="#edit-domain">
                            <i class="orange ace-icon fa fa-globe bigger-125"></i>
                            域名设置
                        </a>
                    </li> 
                </ul>
                <div class="tab-content profile-edit-tab-content">
                    <div id="edit-settings" class="tab-pane active">
                        @using (Html.BeginRouteForm("editStore", FormMethod.Post, new { @class = "form-horizontal", id = "formStore", onsubmit = "return false;" }))
                        {
                            @Html.AntiForgeryToken()
                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right" for="form-field-username">显示名称</label>
                                <div class="col-sm-4">
                                    @Html.TextBoxFor(m => m.Name, new { @class = "col-xs-12 col-sm-10", placeholder = "显示名称" })
                                    @Html.ValidationMessageFor(m => m.Name)
                                </div>
                            </div>
                            <div class="space-4"></div>

                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right" for="form-field-username">图标样式</label>
                                <div class="col-sm-4">
                                    @Html.TextBoxFor(m => m.IconClass, new { @class = "col-xs-12 col-sm-10", placeholder = "图标样式" })
                                    @Html.ValidationMessageFor(m => m.IconClass)
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right" for="form-field-username">公司名称</label>
                                <div class="col-sm-6">
                                    @Html.TextBoxFor(m => m.CompanyName, new { @class = "col-xs-12 col-sm-10", placeholder = "公司名称" })
                                    @Html.ValidationMessageFor(m => m.CompanyName)
                                </div>
                            </div>
                            <div class="space-4"></div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right" for="form-field-username">Https</label>
                                <div class="col-sm-4">
                                    <label>
                                        <input type="checkbox" id="SslEnabled" name="SslEnabled" value="true" @(Model!=null && Model.SslEnabled?"checked=checked":"") class="ace">
                                        <span class="lbl"> 只允许Https连接，需设置Https</span>
                                    </label>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right" for="form-field-username">停用</label>
                                <div class="col-sm-4">
                                    <label class="inline">
                                        <input type="checkbox" id="Disabled" name="Disabled" value="true" @(Model!=null && Model.Disabled?"checked=checked":"") class="ace">
                                        <span class="lbl"> 停用系统</span>
                                    </label>
                                </div>
                            </div>
                            <div class="clearfix form-actions">
                                <div class="col-md-offset-3 col-md-9">
                                    <button class="btn btn-info" type="submit">
                                        <i class="ace-icon fa fa-check bigger-110"></i>
                                        保存
                                    </button>
                                </div>
                            </div>
                        }
                    </div>
                    <div id="edit-domain" class="tab-pane">
                        @Html.Action("SysDomain", "SystemManage")
                    </div> 
                </div>
            </div>
        </div>
    </div> 
<script>
    $(function () {
        $('#formStore').submit(function () {
            if ($(this).valid()) {
                $(this).ajaxSubmit(function (data) {
                    $.modal.gritter(data)
                });
            }
        });
    });
</script>