Mangix.Mvc/Mangix.Admin/Areas/Admin/Controllers/UserController.cs
using Mangix.Admin.Framework.Controllers;
using Mangix.Admin.Framework.Menu;
using Mangix.Mapping.SysUser;
using Mangix.Services.SysUser;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mangix.Admin.Framework.Datatable;
using Mangix.Mapping;
using Mangix.Core.Encyption;
using Mangix.Core.Librs;
using Mangix.Admin.Framework.Controllers.Admin;

namespace Mangix.Admin.Area.Admin.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [RoutePrefix("user")]
    public class UserController : BaseAdminController
    {
        // GET: User
        private ISysUserService _sysUserService;

        public UserController(ISysUserService sysUserService)
        {
            this._sysUserService = sysUserService;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="arg"></param>
        /// <param name="page"></param>
        /// <param name="size"></param>
        /// <returns></returns>
        [Descriper("系统用户", true, "menu-icon fa fa-caret-right", FatherResource = "Mangix.Admin.Area.Admin.Controllers.SystemManageController")]
        [Route("", Name = "userIndex")]
        public ActionResult UserIndex(SysUserSearchArg arg, int page = 1, int size = 20)
        {
            var pageList = _sysUserService.searchUser(arg, page, size);
            var dataSource = pageList.toDataSourceResult<Entities.SysUser>("userIndex", arg);
            return View(dataSource);
        }

        /// <summary>
        /// 编辑用户
        /// </summary>
        /// <param name="id"></param>
        /// <param name="returnUrl"></param>
        /// <returns></returns>
        [HttpGet]
        [Route("edit", Name = "editUser")]
        [Descriper("编辑系统用户", false, FatherResource = "Mangix.Admin.Area.Admin.Controllers.UserController.UserIndex")]
        public ActionResult EditUser(Guid? id, string returnUrl = null)
        {
            ViewBag.ReturnUrl = Url.IsLocalUrl(returnUrl) ? returnUrl : Url.RouteUrl("userIndex");
            SysUserMapping model = new SysUserMapping();
            if (id.HasValue && id.Value != Guid.Empty)
            {
                var item = _sysUserService.getUserById(id.Value);
                if (item != null)
                    return View(item.toModel());
            }
            return View(model);
        }

        [HttpPost]
        [Route("edit")]
        public ActionResult EditUser(SysUserMapping model, string returnUrl = null)
        {
            ViewBag.ReturnUrl = Url.IsLocalUrl(returnUrl) ? returnUrl : Url.RouteUrl("userIndex");
            if (!ModelState.IsValid)
                return View(model);
            if (!String.IsNullOrEmpty(model.MobilePhone))
                model.MobilePhone = StringUitls.toDBC(model.MobilePhone);
            model.Name = model.Name.Trim();

            if (model.Id == Guid.Empty)
            {
                model.Id = Guid.NewGuid();
                model.CreationTime = DateTime.Now;
                model.Salt = EncryptorHelper.CreateSaltKey();
                model.Account = StringUitls.toDBC(model.Account.Trim());
                model.Enabled = true;
                model.IsAdmin = false;
                model.Password = EncryptorHelper.GetMD5(model.Account + model.Salt);
                model.Creator = WorkContext.CurrentUser.Id;
                _sysUserService.insertSysUser(model.toEntity());
            }
            else
            {
                model.ModifiedTime = DateTime.Now;
                model.Modifier = WorkContext.CurrentUser.Id;
                _sysUserService.updateSysUser(model.toEntity());
            }
            return Redirect(ViewBag.ReturnUrl);
        }


        /// <summary>
        /// 设置启用与禁用账号
        /// </summary>
        /// <param name="id"></param>
        /// <param name="enabled"></param>
        /// <returns></returns>
        [Route("enabled", Name = "enabled")]
        [Descriper("设置启用与禁用账号", false, FatherResource = "Mangix.Admin.Area.Admin.Controllers.UserController.UserIndex")]
        public JsonResult Enabled(Guid id, bool enabled)
        {
            _sysUserService.enabled(id, enabled, WorkContext.CurrentUser.Id);
            AjaxData.Message = "启用禁用设置完成";
            AjaxData.Status = true;
            return Json(AjaxData, JsonRequestBehavior.DenyGet);
        }


        /// <summary>
        /// 设置登录锁解锁与锁定
        /// </summary>
        /// <param name="id"></param>
        /// <param name="enabled"></param>
        /// <returns></returns>
        [Route("loginLock", Name = "loginLock")]
        [Descriper("设置登录锁解锁与锁定", false, FatherResource = "Mangix.Admin.Area.Admin.Controllers.UserController.UserIndex")]
        public JsonResult LoginLock(Guid id, bool loginLock)
        {
            _sysUserService.loginLock(id, loginLock, WorkContext.CurrentUser.Id);
            AjaxData.Message = "登录锁状态设置完成";
            AjaxData.Status = true;
            return Json(AjaxData, JsonRequestBehavior.DenyGet);
        }

        /// <summary>
        /// 删除用户
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Route("delete/{id}", Name = "deleteUser")]
        [Descriper("删除用户", false, FatherResource = "Mangix.Admin.Area.Admin.Controllers.UserController.UserIndex")]
        public JsonResult DeleteUser(Guid id)
        {
            _sysUserService.deleteUser(id, WorkContext.CurrentUser.Id);
            AjaxData.Status = true;
            AjaxData.Message = "删除完成";
            return Json(AjaxData, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 远程验证账号是否存在
        /// </summary>
        /// <param name="id"></param>
        /// <param name="account"></param>
        /// <returns></returns>
        [Route("existAccount", Name = "remoteAccount")]
        [Descriper("远程验证账号是否存在", false, FatherResource = "Mangix.Admin.Area.Admin.Controllers.UserController.UserIndex")]
        public JsonResult RemoteAccount(string account)
        {
            account = account.Trim();
            return Json(!_sysUserService.existAccount(account), JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 重置用户密码
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Route("resetPwd/{id}",Name ="resetPassword")]
        [Descriper("重置用密码", false, FatherResource = "Mangix.Admin.Area.Admin.Controllers.UserController.UserIndex")]
        public JsonResult ResetPassword(Guid id)
        {
            _sysUserService.resetPassword(id,WorkContext.CurrentUser.Id);
            AjaxData.Status = true;
            AjaxData.Message = "用户密码已重置为原始密码";
            return Json(AjaxData, JsonRequestBehavior.AllowGet);
        }
    }
}

Mangix.Mvc/Mangix.Admin/Areas/Admin/Controllers/WidgetController.cs
using Mangix.Admin.Framework.Controllers;
using Mangix.Admin.Framework.Controllers.Admin;
using Mangix.Admin.Framework.Datatable;
using Mangix.Services.SysRole;
using Mangix.Services.SysUser;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mangix.Admin.Area.Admin.Controllers
{
    [RoutePrefix("widget")]
    public class WidgetController : BaseAdminPublicController
    {
        // GET: Widget
        private ISysUserService _sysUserService;
        private ISysRoleService _sysRoleService;

        /// <summary>
        /// 
        /// </summary>
        /// <param name="sysUserService"></param>
        public WidgetController(ISysUserService sysUserService,
            ISysRoleService sysRoleService)
        {
            this._sysUserService = sysUserService;
            this._sysRoleService = sysRoleService;
        }

        /// <summary>
        /// 系统用户下拉选择框
        /// </summary>
        /// <returns></returns>
        [ChildActionOnly]
        public PartialViewResult ChosenUser(Guid? id)
        {
            if (id != null && id.Value != Guid.Empty)
            {
                var item = _sysUserService.getUserById(id.Value);
                return PartialView(item);
            }
            return PartialView();
        }

        /// <summary>
        /// select2下拉操作员
        /// </summary>
        /// <param name="q"></param>
        /// <returns></returns>
        [Route("selset2/users", Name = "userData")]
        public JsonResult UserData(string q)
        {
            var list = _sysUserService.searchUser(new Mapping.SysUser.SysUserSearchArg() { q = q }, 1, 20);
            if (list != null && list.Any())
            {
                var result = list.Select(item => new Select2Model { id = item.Id.ToString(), text = item.Name }).ToList();
                result.Insert(0, new Select2Model { id = "", text = "选择操作员" });
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            return Json(null, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 角色下拉框
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [ChildActionOnly]
        public PartialViewResult SelectRole(Guid ? id)
        {
            ViewBag.RoleId = id;
            return PartialView(_sysRoleService.getAllRoles());
        }




    }
}

Mangix.Mvc/Mangix.Admin/Areas/Admin/Views/User/EditUser.cshtml
@using Mangix.Admin.Framework.Mvc.Html
@model Mangix.Mapping.SysUser.SysUserMapping
@{
    ViewBag.Title = "编辑系统用户";
} 
    <h1>@ViewBag.Title</h1>
    <hr />
    <div class="row">
        <div class="col-sm-12">
            @using (Html.BeginRouteForm("editUser", new { returnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal" }))
            {
                @Html.HiddenFor(m => m.Id) 
                @Html.AntiForgeryToken()
                if (Model.Id == Guid.Empty)
                {
                    <div class="form-group">
                        <label class="col-sm-2 control-label no-padding-right">账号 @Html.RequiredSpan()</label>
                        <div class="col-sm-9">
                            @Html.TextBoxFor(m => m.Account, new { @class = "col-xs-10 col-sm-5", placeholder = "用户账号" })
                            @Html.ValidationMessageFor(m => m.Account)
                        </div>
                    </div>
                }
                else
                {
                    <div class="form-group">
                        <label class="col-sm-2 control-label no-padding-right">账号</label>
                        <div class="col-sm-9"> 
                            @Html.HiddenFor(m => m.Account)
                            <b>@Model.Account</b>
                        </div>
                    </div>
                }
                <div class="form-group">
                    <label class="col-sm-2 control-label no-padding-right">姓名 @Html.RequiredSpan()</label>
                    <div class="col-sm-9">
                        @Html.TextBoxFor(m => m.Name, new { @class = "col-xs-10 col-sm-5", placeholder = "姓名" })
                        @Html.ValidationMessageFor(m => m.Name)
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label no-padding-right">手机号码</label>
                    <div class="col-sm-9">
                        @Html.TextBoxFor(m => m.MobilePhone, new { @class = "col-xs-10 col-sm-5", placeholder = "手机号码" })
                        @Html.ValidationMessageFor(m => m.MobilePhone)
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label no-padding-right">邮箱地址</label>
                    <div class="col-sm-9">
                        @Html.TextBoxFor(m => m.Email, new { @class = "col-xs-10 col-sm-5", placeholder = "邮箱地址" })
                        @Html.ValidationMessageFor(m => m.Email)
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label no-padding-right">性别</label>
                    <div class="radio">
                        <label>
                            @Html.RadioButtonFor(m => m.Sex, "男", new { @class = "ace", id = "sex1" })
                            <span class="lbl"> 男</span>
                        </label>
                        <label>
                            @Html.RadioButtonFor(m => m.Sex, "女", new { @class = "ace", id = "sex2" })
                            <span class="lbl"> 女</span>
                        </label>
                    </div>
                </div>
                <div class="col-md-offset-2 col-md-9">
                    <button class="btn btn-info" type="submit">
                        <i class="ace-icon fa fa-check bigger-110"></i>
                        提交
                    </button>
                </div>
            }
        </div>
    </div> 

Mangix.Mvc/Mangix.Admin/Areas/Admin/Views/User/UserIndex.cshtml
@model Mangix.Admin.Framework.Datatable.DataSourceResult<Mangix.Entities.SysUser>
@{
    var arg = Model.SearchArg as Mangix.Mapping.SysUser.SysUserSearchArg;
    ViewBag.Title = "系统用户列表";
}  
    <h1>@ViewBag.Title</h1>
    <hr />
    <div class="row">
        <div class="col-sm-12">
            @PermissionRouteLinkIcon("添加系统用户", "editUser", new RouteValueDictionary(new { returnUrl = Request.RawUrl }), new { @class = "btn btn-sm btn-pink " }, new { @class = "glyphicon glyphicon-plus" })
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    @using (Html.BeginRouteForm("userIndex", new { }, FormMethod.Get, new { @class = "form-inline" }))
                    {
                        <label>关键字</label>
                        <input type="text" class="form-control" style="width:220px;" placeholder="账号、姓名、邮箱、手机号">
                        <label>操作员</label>
                        @Html.Action("ChosenUser", "Widget", new { id = arg.suid })
                        <label>角色</label>
                        @Html.Action("SelectRole", "Widget", new { id = arg.roleId })
                        <button type="submit" class="btn btn-purple btn-sm">
                            查询
                            <i class="ace-icon fa fa-search icon-on-right bigger-110"></i>
                        </button>
                    }
                </div>
            </div>
        </div>
    </div>

    @if (Model != null && Model.Data != null)
    {
        <div class="row">
            <div class="col-sm-12">
                <table id="user_datatable" class="table table-striped table-bordered table-hover dataTable no-footer">
                    <thead>
                        <tr>
                            <th width="150px">账号</th>
                            <th width="100px">姓名</th>
                            <th width="110px">手机号</th>
                            <th width="60px">性别</th>
                            <th width="150px">活动时间</th>
                            <th width="100px">启用</th>
                            <th width="120px">登录锁</th>
                            <th width="50px;">密码</th>
                            <th>操作</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Data)
                        {
                            <tr>
                                <td>@item.Account</td>
                                <td>@item.Name</td>
                                <td>@item.MobilePhone</td>
                                <td>@item.Sex</td>
                                <td>@(item.LastActivityTime?.ToString("MM:dd HH;mm:ss"))</td>
                                <td>
                                    @if (!item.IsAdmin)
                                    {
                                        if (item.Enabled)
                                        {
                                            <label>
                                                <input name="enabled" class="ace ace-switch ace-switch-7 user_enabled" value="@item.Id" type="checkbox" checked="checked">
                                                <span class="lbl"></span>
                                            </label>
                                        }
                                        else
                                        {
                                            <label>
                                                <input name="enabled" class="ace ace-switch ace-switch-7 user_enabled" value="@item.Id" type="checkbox">
                                                <span class="lbl"></span>
                                            </label>
                                        }
                                    }
                                </td>
                                <td>
                                    @if (item.LoginLock)
                                    {
                                        <label>
                                            <input name="lock" value="@item.Id" class="ace ace-switch ace-switch-5 user_lock" type="checkbox" checked="checked">
                                            <span class="lbl"></span>
                                        </label>
                                        if (item.AllowLoginTime.HasValue && item.AllowLoginTime > DateTime.Now)
                                        {
                                            <span class="badge">@((int)(item.AllowLoginTime.Value - DateTime.Now).TotalMinutes + 1)分</span>
                                        }
                                    }
                                    else
                                    {
                                        <label data-toggle="tooltip" data-placement="left" title="Tooltip on left">
                                            <input name="lock" value="@item.Id" class="ace ace-switch ace-switch-5 user_lock" type="checkbox">
                                            <span class="lbl"></span>
                                        </label>
                                    }
                                </td>
                                <td>
                                    @if (!item.IsAdmin)
                                {
                                    @PermissionRouteLinkIcon("", "resetPassword", new RouteValueDictionary(new { id = item.Id }), new { @class = "btn btn-xs btn-warning btnResetPwd", title = "重置密码" }, new { @class = "ace-icon fa fa-undo" })
                                }
                            </td>
                            <td>
                                @PermissionRouteLinkIcon("", "editUser", new RouteValueDictionary(new { id = item.Id, returnUrl = Request.RawUrl }), new { @class = "btn btn-xs btn-info", title = "修改资料" }, new { @class = "glyphicon glyphicon-pencil" })
                                @if (!item.IsAdmin)
                                {
                                    @PermissionRouteLinkIcon("角色", "editUserRole", new RouteValueDictionary(new { id = item.Id, returnUrl = Request.RawUrl }), new { @class = "btn btn-xs btn-grey", title = "设置角色" }, new { @class = "glyphicon glyphicon-user" })
                                }
                                @if (!item.IsAdmin)
                                {
                                    @PermissionRouteLinkIcon("", "deleteUser", new RouteValueDictionary(new { id = item.Id }), new { @class = "btn btn-xs btn-danger btnDelete", title = "删除用户" }, new { @class = "glyphicon glyphicon-trash" })
                                }
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
                @Pagination(Model.Paging)
            </div>
        </div>
        @Html.AntiForgeryToken()
        <script>
            $(function () {
                $('.user_lock').on('click', function () {
                    //锁定与解锁
                    $.post('@Url.RouteUrl("loginLock")', { id: $(this).val(), loginLock: this.checked, __RequestVerificationToken: $('[name="__RequestVerificationToken"]').val() }, function (data) {
                        $.modal.gritter(data);
                    });
                });
                $('.user_enabled').click(function () {
                    //启用冻结
                    $.post('@Url.RouteUrl("enabled")', { id: $(this).val(), enabled: this.checked, __RequestVerificationToken: $('[name="__RequestVerificationToken"]').val() }, function (data) {
                        $.modal.gritter(data);
                    });
                });

                $(".btnDelete").click(function (e) {
                    e.preventDefault();
                    var url = $(this).attr('href');
                    $.modal.confirm('删除后将不可恢复，您确定要删除此用户？', function () {
                        $.get(url, function (data) {
                            $.modal.alert(data);
                        });
                    });
                });
                $('.btnResetPwd').click(function (e) {
                    e.preventDefault();
                    var url = $(this).attr('href');
                    $.modal.confirm('您确定要重置次用户密码？', function () {
                        $.get(url, function (data) {
                            $.modal.gritter(data);
                        });
                    });
                });

            });
        </script>
    } 